export const FETCH_ALL_PRODUCTS_REQUEST = "FETCH_ALL_PRODUCTS_REQUEST";
export const FETCH_ALL_PRODUCTS_SUCCESS = "FETCH_ALL_PRODUCTS_SUCCESS";
export const FETCH_ALL_PRODUCTS_FAIL = "FETCH_ALL_PRODUCTS_FAIL";
export const ADD_TO_CART_PRODUCT = "ADD_TO_CART_PRODUCT";
export const CART_PRODUCT_DELETE = "CART_PRODUCT_DELETE";
export const PRODUCT_QTY_DECREASE = "PRODUCT_QTY_DECREASE";
export const GET_CATEGORY_PRODUCT = "GET_CATEGORY_PRODUCT";

export const BASE_URL = "https://fakestoreapi.com";


// export const FETCH_NOTIFICATION_DELETE = "FETCH_NOTIFICATION_DELETE";
// export const GET_NOTIFICATION_LIST = "GET_NOTIFICATION_LIST";
// export const GET_NOTIFICATION_UPDATE_LIST = "GET_NOTIFICATION_UPDATE_LIST";